import java.io.PrintWriter;

import java.util.Comparator;
import java.util.Iterator;

/**
 * Code for tracing what happens in a failed test.
 * 
 * @author Samuel A. Rebelsky
 * @author Your Name Here
 */
public class BSTTrace
{
  // +-------+-----------------------------------------------------------
  // | Notes |
  // +-------+ 

  /*
     This code is closely based on code by Samuel A. Rebelsky from
     BSTExpt.java from exam 2 of the fall 2013 section of Grinnell's 
     CSC 207.
   */

  // +------+------------------------------------------------------------
  // | Main |
  // +------+

  public static void main(String[] args)
    throws Exception
  {
    PrintWriter pen = new PrintWriter(System.out, true);
    BST<String, String> dict = new BST<String, String>(new Comparator<String>()
      {
        public int compare(String left, String right)
        {
          return left.compareTo(right);
        } // compare(String, String)
      });

    // Sample code generated by reportError
    pen.println("adding tiger");
    dict.set("t", "tiger");
    dict.dump(pen);
    pen.println("adding orangutan");
    dict.set("o", "orangutan");
    dict.dump(pen);
    pen.println("adding horse");
    dict.set("h", "horse");
    dict.dump(pen);
    pen.println("adding gnu");
    dict.set("g", "gnu");
    dict.dump(pen);
    pen.println("adding vicuna");
    dict.set("v", "vicuna");
    dict.dump(pen);
    pen.println("adding gnu");
    dict.set("g", "gnu");
    dict.dump(pen);
    pen.println("adding iguana");
    dict.set("i", "iguana");
    dict.dump(pen);
    pen.println("adding flying squirrel");
    dict.set("f", "flying squirrel");
    dict.dump(pen);
    pen.println("adding red fox");
    dict.set("r", "red fox");
    dict.dump(pen);
    pen.println("removing a");
    dict.remove("a");
    dict.dump(pen);

  } // main(String[])
  // +-----------+-------------------------------------------------------
  // | Utilities |
  // +-----------+

} // BSTTrace
