import java.io.PrintWriter;

import java.util.Comparator;
import java.util.Iterator;

/**
 * Code for tracing what happens in a failed test.
 * 
 * @author Samuel A. Rebelsky
 * @author Your Name Here
 */
public class BSTTrace
{
  // +-------+-----------------------------------------------------------
  // | Notes |
  // +-------+ 

  /*
     This code is closely based on code by Samuel A. Rebelsky from
     BSTExpt.java from exam 2 of the fall 2013 section of Grinnell's 
     CSC 207.
   */

  // +------+------------------------------------------------------------
  // | Main |
  // +------+

  public static void main(String[] args)
    throws Exception
  {
    PrintWriter pen = new PrintWriter(System.out, true);
    BST<String, String> dict = new BST<String, String>(new Comparator<String>()
      {
        public int compare(String left, String right)
        {
          return left.compareTo(right);
        } // compare(String, String)
      });
    
    // Sample code generated by reportError
    pen.println("adding zebra");
    dict.set("z","zebra");
    dict.dump(pen);
    pen.println("removing z");
    dict.remove("z");
    dict.dump(pen);
    pen.println("adding vicuna");
    dict.set("v","vicuna");
    dict.dump(pen);
    pen.println("removing w");
    dict.remove("w");
    dict.dump(pen);
    pen.println("adding dingo");
    dict.set("d","dingo");
    dict.dump(pen);
    pen.println("adding wombat");
    dict.set("w","wombat");
    dict.dump(pen);
    pen.println("adding llama");
    dict.set("l","llama");
    dict.dump(pen);
    pen.println("adding goat");
    dict.set("g","goat");
    dict.dump(pen);
    pen.println("adding dingo");
    dict.set("d","dingo");
    dict.dump(pen);
    pen.println("adding buffalo");
    dict.set("b","buffalo");
    dict.dump(pen);
    pen.println("adding buffalo");
    dict.set("b","buffalo");
    dict.dump(pen);
    pen.println("removing i");
    dict.remove("i");
    dict.dump(pen);

    dict.dump(pen);
  } // main(String[])
  // +-----------+-------------------------------------------------------
  // | Utilities |
  // +-----------+

} // BSTTrace
